### ISSUE TITLE
Editor always active by start

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#804] opened 2020-01-28 12:26 UTC
The editor is active by start although the option is set to `"isActive": false`.

**Comment by Grammostola** [comment] 2020-01-29 10:13
I was unable to reproduce using the latest Origo, editor example, i.e setting "isActive": false disables the editor toolbar when the page loads. Setting it to true or "cat" enables it. If you are using the latest Origo, does it work if your map definition json looks mostly like the examples?

**Comment by asemoller** [comment] 2020-01-29 12:27
Sorry for the bad explanation and the misleading title for the issue. The editor icon is displayed like it's active (in other word: it's blue) although `"isActive"` it is set to `false`, so the toolbar is disabled like you mentioned. This is the latest Origo using editor.json in examples. Can you reproduce this @Grammostola?

**Comment by Grammostola** [comment] 2020-01-30 12:44
Acknowledged @asemoller. Thanks for the explanation. Will look into it.

**Comment by Grammostola** [comment] 2020-01-30 15:50
Issue identified. PR for fix will arrive on the morrow.

**Comment by MattiasSp** [comment] 2020-02-05 16:02
Hey! I just want to add that I had this same issue after updating to the latest 2.1.0 release build, and that the enabled state on the editor also caused my featureinfo popups to be blocked until I clicked the pen to deactivate editing.

Also, thanks for the speedy fix! That edit worked like a charm on the 2.1.0 release as well :)

**Comment by Grammostola** [comment] 2020-02-18 13:41
Thanks for letting us know @mattiasSp :  ) Closing.

**Closed by Grammostola** 2020-02-18 13:41 UTC
