### ISSUE TITLE
Measure sketch is not displayed with GPS-active

### ISSUE THREAD

**Issue by Lund-gren** [origo-map/origo#140] opened 2016-10-28 11:09 UTC
When the GPS is active and you start to measure the "mouse-circle" (insertion circle at the mousepointer), "sketch" and feature are not drawn

**Comment by tonnyandersson** [comment] 2016-10-28 13:36
I believe this is caused by the setActive() function in featureinfo.js. The function calls Viewer.removeOverlays() which will remove all overlays, including the geoposition overlay and the measure tool pointer and sketch features.

The geoposition overlay must be excluded from the overlays to be removed, at one point or another.

**Comment by afogelberg** [comment] 2016-10-29 10:46
We can solve this by dispatching an remove overlay event and corresponding listener in those controls that are using feature info overlays. Then we van change to not remove all overlays.

**Comment by afogelberg** [comment] 2017-04-05 10:11
Fixed with #223

**Closed by afogelberg** 2017-04-05 10:11 UTC
