### ISSUE TITLE
Abstract design

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#582] opened 2019-03-13 19:07 UTC
The layer abstract text could have a little bit of margin on the sides and maybee different font-size  
![image](https://user-images.githubusercontent.com/24228538/54381211-7b088600-468d-11e9-831f-82086994530b.png)

**Comment by mulfvik** [comment] 2019-03-13 19:09
Is there a way to preserve the abstract text for background maps?

**Comment by jokd** [comment] 2019-03-14 10:40
I agree on the font size but not so sure bout the margins. 
Perhaps the abstract for the backgrounds should be triggered when clicking on an active background layer? Right now there seems to be no such functionality.

**Comment by mulfvik** [comment] 2019-03-14 18:18
It can be hard to find the abstract this way. Maybee that if there is an abstract the legend expands above background maps selectors and push the other stuff up a bit?

**Comment by markus659** [comment] 2019-03-20 12:50
I could not repeat this issue using the latest Origo master. Can you reproduce it using default Origo @mulfvik?

**Comment by mulfvik** [comment] 2019-03-20 19:26
@markus659 Thats weird but good stuff. New clone looks much better. 
![image](https://user-images.githubusercontent.com/24228538/54713193-58bfae00-4b4e-11e9-86e9-021c9caa45e3.png)

**Comment by markus659** [comment] 2019-03-21 09:46
Great! I'll close this issue for now at least then.

**Closed by markus659** 2019-03-21 09:46 UTC
