### ISSUE TITLE
Background maps abstract flutter

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#955] opened 2020-06-09 15:48 UTC
Background maps abstract flutter

`"attribution": "&copy Lantmäteriet Geodatasamverkan | Strängnäs kommun",
      "abstract": "<p>Information om när detta fotot är taget finner du <a href='https://geolex.etjanster.lantmateriet.se/?e=614815&n=6580926&z=7&profile=default_geolex_orto_latest_year_noauth' target='_blank'>här</a> på Lantmäteriets tjänst GeoLex.</p>"`

![captured](https://user-images.githubusercontent.com/24228538/84169644-24991b80-aa79-11ea-8899-fb5b2bc6b617.gif)

**Comment by tonnyandersson** [comment] 2020-06-10 09:42
@mulfvik I think this (and #957) is caused by some weird stuff going on in the footer. I think the fluttering stops if you remove the position control, which indicates the culprit may reside in the footer.

**Comment by jokd** [comment] 2020-06-10 09:48
Perhaps somehow related to #914 as well.

**Comment by mulfvik** [comment] 2020-07-13 11:49
IE doesnt activate scroll with PR #958

**Comment by jokd** [comment] 2020-09-07 12:04
Stumbled upon a similar issue where the legend fluttered when panning. Removing the o-scrollbar class for the legendCollapse div solved it in the debugger at least.

**Comment by daRasmussen** [comment] 2020-09-08 07:22
@jokd I am not able to reproduce this is issue, what config, version of origo and browser are you using? 

No flutter here: 
[`Strangnas extern`](https://kartor.strangnas.se/extern/#layers=topowebbkartan/v/1/s/0,gis_kommunmask/v/1/s/0&center=180064,6584919&zoom=4&map=extern)

**Comment by jokd** [comment] 2020-09-08 07:25
You must have layer names with length around the limit what fits in one row. Check this: https://gi.karlstad.se/jnft/cykelkartan/

**Comment by jokd** [comment] 2020-12-01 08:47
@tonnyandersson Can we close this now?

**Comment by tonnyandersson** [comment] 2020-12-01 09:01
@jokd I believe we can.

**Closed** 2020-12-01 09:01 UTC
Labels: PR accepted, bug
