### ISSUE TITLE
information window does not show properly in png in print function

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1596] opened 2022-09-13 14:35 UTC
**Describe the bug**
After we searched an object from the search function the map will be zoomed into the object in the map and there is a information window pop up to show the object's attributes. 

![image](https://user-images.githubusercontent.com/36880995/189930424-c0a60c03-2abd-4892-96f3-9e33e79514be.png)

Then when we go to the print function and save the map together with the pop-up information window to a picture (png), the pop-up window cannot be shown properly: 
![image](https://user-images.githubusercontent.com/36880995/189931147-039cb0c7-1cbd-4c3b-8c13-c72d150b7f4e.png)

But when we save the map to a pdf then the pop-up window is shown correctly:
![image](https://user-images.githubusercontent.com/36880995/189930842-88b5dfc7-f043-409a-aadb-a2b5df28e471.png)

**Comment by jokd** [comment] 2022-09-13 15:49
I am unable to reproduce this, the popup looks decent when exporting as png. However the borders around the legend and popup are a bit thick and the icon for closing the popup is missing
![image](https://user-images.githubusercontent.com/6848075/189947750-36ca5982-7847-4441-bf00-dbd1096cd240.png)

**Comment by Grammostola** [comment] 2022-09-19 09:29
I've seen the same thing as @jokd

**Comment by leafisfalling** [comment] 2022-09-23 07:56
several of us in our organisation tested it and we have the same problem. We will test it again and see if there is something strange in our environment.

**Comment by jokd** [comment] 2022-11-09 12:20
@leafisfalling Is this still an issue and if so, can you provide a config so we can have a look at it?

**Comment by jokd** [comment] 2023-01-27 07:00
@leafisfalling Can you please test your config on the master branch to see if the issue remains?

**Comment by leafisfalling** [comment] 2023-04-04 06:54
@jokd 
I am terribly sorry. I did not see your messages since nov 2022 until now. I tried it in version 2.6 and we still have the same problem.

**Comment by jokd** [comment] 2023-04-04 07:04
And you use the correct .css as well?
Is the map public?

**Comment by jokd** [comment] 2023-04-04 07:30
If you are using a build of Origo, <link href="css/style.css" rel="stylesheet"> in your index.html needs to point to the .css generated in the css-folder when making the build.

If you are running in dev mode it should automatically be the correct css file.

**Comment by leafisfalling** [comment] 2023-04-04 14:34
@jokd Thanks for instructions. I check the css and it seems nothing wrong with it in our html file...

**Comment by leafisfalling** [comment] 2023-04-05 08:47
@jokd We have two css and we tested to remove one of them (the one that we used for our "Help" chapters inte menu, which developed by Sundsvall) in the latest master and the the print function for png works well again. so I guess there is something in the css from Sundsvall which is not compatible with origo? @johnnyblasta, do you have any idea what can go wrong?

**Comment by johnnyblasta** [comment] 2023-04-05 09:13
> @jokd We have two css and we tested to remove one of them (the one that we used for our "Help" chapters inte menu, which developed by Sundsvall) in the latest master and the the print function for png works well again. so I guess there is something in the css from Sundsvall which is not compatible with origo? @johnnyblasta, do you have any idea what can go wrong?

@leafisfalling nice one, finding a cause. I'll have a look what's going on.

**Comment by johnnyblasta** [comment] 2023-04-05 12:22
@leafisfalling 
Do this in the help.css to solve the problem.

Find this code:
```
/*--------------------------------------------------------------------------------*/
/* Visa och dölj info-framen -----------------------------------------------------*/
/*--------------------------------------------------------------------------------*/
iframe{
  border-style: none;
  width: 100%;
  /*height: calc(100% - 0.2em);*/
  height: 0;
  background-image: url(../img/loading.gif);
  background-repeat: no-repeat;
  background-size: 7em;
  background-position-x: 5em;
  background-position-y: 2em;
}
#infoFrame{
  height: calc(100% - 0.2em);
}
```

Exchange to this:
```
/*--------------------------------------------------------------------------------*/
/* Visa och dölj info-framen -----------------------------------------------------*/
/*--------------------------------------------------------------------------------*/
#infoFrame{
  border-style: none;
  width: 100%;
  height: calc(100% - 0.2em);
  background-image: url(../img/loading.gif);
  background-repeat: no-repeat;
  background-size: 7em;
  background-position-x: 5em;
  background-position-y: 2em;
}
```

**Comment by leafisfalling** [comment] 2023-04-06 07:01
@johnnyblasta thanks! it works.

**Comment by johnnyblasta** [comment] 2023-04-06 07:23
Closing this since it was not caused by code in Origo repository, but an external stylesheet that changed style on HTML element instead of as a class or a specific id.

**Closed by johnnyblasta** 2023-04-06 07:23 UTC
Labels: bug, PR accepted
