### ISSUE TITLE
Draw function

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#389] opened 2018-01-18 08:38 UTC
Lets the user draw a line, a point or area or text in the map. These objects will disappear when you hide the draw-tool.

Developed for the Open eMap version of Origo.

**Comment by afogelberg** [comment] 2018-01-18 09:15
Duplicate of #193 ? As I understand the Open eMap control is based on https://github.com/origo-map/origo/tree/draw

**Comment by tonnyandersson** [comment] 2018-01-18 11:04
@afogelberg You're right, it is a duplicate, with a few additions to the original code.

**Comment by afogelberg** [comment] 2018-01-18 11:34
Can we close this then?

**Comment by tonnyandersson** [comment] 2018-01-18 12:09
I guess so.

**Closed** 2018-01-18 12:09 UTC
